apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaelan-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kaelan-app
  template:
    metadata:
      labels:
        app: kaelan-app
    spec:
      containers:
      - name: kaelan-app
        image: kaelan-app:1.0.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: kaelan-app-lb
spec:
  selector:
    app: kaelan-app
  ports:
    - name: http
      port: 8080
      targetPort: 3000
  type: LoadBalancer